on:
  workflow_dispatch:

name: Release Minor

jobs:
  build:
    name: Create Release Minor
    permissions:
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate a build system
        run: cmake -S . -B ./build
      - name: Build project
        run: make -j --no-print-directory -C build

# ==============================
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-minor.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
