name: units-tests

on:
  push:
    branches:
      - "dev"
      - "feat/CI/CD"

jobs:
  test:
    # runs-on: [ubuntu-latest, windows-latest]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cmake -DTESTS=on -S . -B ./build
      - name: Test
        run: make -j --no-print-directory -C build tests-run-cevy
      # - name: format
      #   run: 